apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-cloudplatform
spec:
  package: {{ .Values.providers.cloudplatform.package }}
  runtimeConfigRef:
    name: gcp-fast-poll
