apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp-secretmanager
spec:
  package: {{ .Values.providers.secretmanager.package }}
  runtimeConfigRef:
    name: gcp-fast-poll
