// Package gcp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package gcp

// XGatewayGCPSpec defines model for XGatewayGCPSpec.
type XGatewayGCPSpec struct {
	Address *struct {
		External *struct {
			Ip   *string `json:"ip,omitempty"`
			Name *string `json:"name,omitempty"`
		} `json:"external,omitempty"`
		Type *string `json:"type,omitempty"`
	} `json:"address,omitempty"`
	AllowedPorts *[]struct {
		Port     int    `json:"port"`
		Protocol string `json:"protocol"`
	} `json:"allowedPorts,omitempty"`
	DiskSizeGB         *int    `json:"diskSizeGB,omitempty"`
	EnableOsLogin      *bool   `json:"enableOsLogin,omitempty"`
	Image              *string `json:"image,omitempty"`
	MachineType        string  `json:"machineType"`
	ProjectID          *string `json:"projectID,omitempty"`
	ProviderConfigName *string `json:"providerConfigName,omitempty"`
	Region             string  `json:"region"`
	SecretId           *string `json:"secretId,omitempty"`
	ServiceAccountId   *string `json:"serviceAccountId,omitempty"`
	SharedNetworkName  string  `json:"sharedNetworkName"`
	Spot               *bool   `json:"spot,omitempty"`
	TrafficPolicy      *string `json:"trafficPolicy,omitempty"`
	UserData           *string `json:"userData,omitempty"`
	WgGatewayAddress   *string `json:"wgGatewayAddress,omitempty"`
	WgKeySecretRef     *struct {
		Key  string `json:"key"`
		Name string `json:"name"`
	} `json:"wgKeySecretRef,omitempty"`
	WgLinkAddress *string `json:"wgLinkAddress,omitempty"`
	WgListenPort  int     `json:"wgListenPort"`
	WgMTU         int     `json:"wgMTU"`
	WgSubnet      *string `json:"wgSubnet,omitempty"`
	Zone          string  `json:"zone"`
}

// XGatewayGCPStatus defines model for XGatewayGCPStatus.
type XGatewayGCPStatus struct {
	Address             *string `json:"address,omitempty"`
	Message             *string `json:"message,omitempty"`
	ServiceAccountEmail *string `json:"serviceAccountEmail,omitempty"`
}
