// Package gcp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package gcp

// XGatewayGCPSpec defines model for XGatewayGCPSpec.
type XGatewayGCPSpec struct {
	AllowedPorts *[]struct {
		Port     int    `json:"port"`
		Protocol string `json:"protocol"`
	} `json:"allowedPorts,omitempty"`
	DiskSizeGB        *int    `json:"diskSizeGB,omitempty"`
	Image             *string `json:"image,omitempty"`
	MachineType       string  `json:"machineType"`
	ProjectID         *string `json:"projectID,omitempty"`
	Region            string  `json:"region"`
	ReservedIP        *bool   `json:"reservedIP,omitempty"`
	SecretId          *string `json:"secretId,omitempty"`
	ServiceAccountId  *string `json:"serviceAccountId,omitempty"`
	SharedNetworkName string  `json:"sharedNetworkName"`
	Spot              *bool   `json:"spot,omitempty"`
	UserData          *string `json:"userData,omitempty"`
	WgGatewayAddress  *string `json:"wgGatewayAddress,omitempty"`
	WgKeySecretRef    *struct {
		Key  string `json:"key"`
		Name string `json:"name"`
	} `json:"wgKeySecretRef,omitempty"`
	WgLinkAddress *string `json:"wgLinkAddress,omitempty"`
	WgListenPort  int     `json:"wgListenPort"`
	WgSubnet      *string `json:"wgSubnet,omitempty"`
	Zone          string  `json:"zone"`
}

// XGatewayGCPStatus defines model for XGatewayGCPStatus.
type XGatewayGCPStatus struct {
	Address             *string `json:"address,omitempty"`
	ServiceAccountEmail *string `json:"serviceAccountEmail,omitempty"`
}
