// Package link implements the in-cluster gateway-link daemon: the cluster end of
// the WireGuard tunnel to the gateway VM. It dials out to the gateway, brings up
// wg0, and programs nftables to DNAT configured public ports arriving on wg0 to
// in-cluster Service ClusterIPs.
//
// The gateway's endpoint is learned at runtime from XGateway.status.address via
// an in-cluster Kubernetes client and re-applied whenever the IP appears or
// changes; the wg0 address and the port forwards remain ConfigMap-driven and
// restart-on-config.
//
// The gateway is the public anchor and masquerades client traffic to its own
// wg0 address, so the link needs no connmark, policy routing, or rp_filter
// changes: replies route natively back out wg0.
package link

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"time"
)

// Config is the process-level configuration for gateway-link, populated from the
// environment via config.Load. The empty envconfig prefix means tags are read
// verbatim.
type Config struct {
	// ConfigPath is the on-disk path to the JSON RuntimeConfig.
	ConfigPath string `envconfig:"GATEWAY_CONFIG_PATH" default:"/etc/cyno/config.json"`
	// WGKeyPath is the path to the WireGuard private key, kept out of the
	// RuntimeConfig so the key Secret and the config ConfigMap can be mounted
	// and rotated independently. It defaults to the "private" key of the link
	// Secret mounted at /etc/cyno/wg/.
	WGKeyPath string `envconfig:"GATEWAY_WG_KEY_PATH" default:"/etc/cyno/wg/private"`
	// PeerPubKeyPath is the path to the gateway's WireGuard public key. The key
	// is generated by the bootstrap Job, so it is delivered via the mounted link
	// Secret (the "peerPublicKey" key) rather than the Helm-templated ConfigMap.
	PeerPubKeyPath string `envconfig:"GATEWAY_WG_PEER_PUBKEY_PATH" default:"/etc/cyno/wg/peerPublicKey"`
	// HealthAddr is the listen address for the readiness HTTP server.
	HealthAddr string `envconfig:"GATEWAY_HEALTH_ADDR" default:":8080"`
	// GatewayName is the name of the XGateway composite resource whose
	// status.address supplies the gateway's public IP.
	GatewayName string `envconfig:"GATEWAY_NAME" required:"true"`
	// GatewayNamespace is the namespace of that XGateway.
	GatewayNamespace string `envconfig:"GATEWAY_NAMESPACE" required:"true"`
	// WGListenPort is the gateway's WireGuard UDP port, joined with the observed
	// gateway IP to form the peer endpoint.
	WGListenPort int `envconfig:"GATEWAY_WG_LISTEN_PORT" required:"true"`
	// ReconcileInterval is how often the link re-reads XGateway.status.address
	// and re-applies the tunnel when the IP appears or changes.
	ReconcileInterval time.Duration `envconfig:"GATEWAY_RECONCILE_INTERVAL" default:"10s"`
}

// RuntimeConfig is the on-disk JSON config describing the WireGuard tunnel and
// the port forwards the link programs into nftables. The WireGuard private key
// is deliberately absent; it is read separately from Config.WGKeyPath.
type RuntimeConfig struct {
	WireGuard WireGuard `json:"wireguard"`
	Forwards  []Forward `json:"forwards"`
}

// WireGuard describes the local wg0 interface and the single gateway peer the
// link dials out to.
type WireGuard struct {
	// Address is the wg0 address in CIDR form (e.g. 10.99.0.2/32).
	Address string `json:"address"`
	// ListenPort is the optional local UDP listen port; 0 lets WireGuard pick
	// an ephemeral port, which is the common case since the link dials out.
	ListenPort int `json:"listenPort"`
	// MTU is the optional wg0 MTU; 0 leaves the kernel default.
	MTU  int  `json:"mtu"`
	Peer Peer `json:"peer"`
}

// Peer is the gateway endpoint the link connects to. The peer's public key is
// generated key material; it is read from Config.PeerPubKeyPath at apply time,
// not carried in this config.
type Peer struct {
	// Endpoint is the gateway's public host:port for the WireGuard handshake. It
	// is optional in the on-disk config: the link's reconcile loop derives it
	// from XGateway.status.address and the configured WG listen port at runtime.
	Endpoint string `json:"endpoint"`
	// AllowedIPs is the set of source ranges accepted from and routed to the
	// peer, typically the wg0 subnet.
	AllowedIPs []string `json:"allowedIPs"`
	// PersistentKeepalive in seconds keeps the NAT pinhole open from the
	// link's side; 0 disables it.
	PersistentKeepalive int `json:"persistentKeepalive"`
}

// Forward maps a public port arriving on wg0 to an in-cluster Service. Service
// is a DNS name resolved to a ClusterIP at apply time; the link does not watch
// for ClusterIP changes (v1 reload is restart-on-config).
type Forward struct {
	Name       string `json:"name"`
	PublicPort int    `json:"publicPort"`
	// Protocol is tcp or udp; it is lowercased during validation.
	Protocol   string `json:"protocol"`
	Service    string `json:"service"`
	TargetPort int    `json:"targetPort"`
}

// LoadRuntimeConfig reads and validates the JSON RuntimeConfig at path. Unknown
// fields are tolerated so older daemons can run against newer config schemas.
func LoadRuntimeConfig(path string) (RuntimeConfig, error) {
	var rc RuntimeConfig
	data, err := os.ReadFile(path)
	if err != nil {
		return rc, fmt.Errorf("read runtime config %s: %w", path, err)
	}
	if err := json.Unmarshal(data, &rc); err != nil {
		return rc, fmt.Errorf("unmarshal runtime config %s: %w", path, err)
	}
	if err := rc.validate(); err != nil {
		return rc, fmt.Errorf("validate runtime config %s: %w", path, err)
	}
	return rc, nil
}

// validate normalizes forward protocols to lowercase in place and rejects
// configs the apply step cannot program: a missing wg0 address, an out-of-range
// or unsupported forward, or two forwards colliding on the same public port and
// protocol. The peer endpoint is intentionally not required here; the reconcile
// loop supplies it at runtime from XGateway.status.address.
func (rc *RuntimeConfig) validate() error {
	if rc.WireGuard.Address == "" {
		return fmt.Errorf("wireguard address is required")
	}

	type key struct {
		port  int
		proto string
	}
	seen := make(map[key]string, len(rc.Forwards))
	for i := range rc.Forwards {
		f := &rc.Forwards[i]
		proto := strings.ToLower(f.Protocol)
		f.Protocol = proto
		if proto != "tcp" && proto != "udp" {
			return fmt.Errorf("forward %q: protocol must be tcp or udp, got %q", f.Name, f.Protocol)
		}
		if f.PublicPort < 1 || f.PublicPort > 65535 {
			return fmt.Errorf("forward %q: public port must be in 1..65535, got %d", f.Name, f.PublicPort)
		}
		if f.TargetPort < 1 || f.TargetPort > 65535 {
			return fmt.Errorf("forward %q: target port must be in 1..65535, got %d", f.Name, f.TargetPort)
		}
		if f.Service == "" {
			return fmt.Errorf("forward %q: service is required", f.Name)
		}
		k := key{port: f.PublicPort, proto: proto}
		if prev, ok := seen[k]; ok {
			return fmt.Errorf("forward %q collides with %q on %s/%d", f.Name, prev, proto, f.PublicPort)
		}
		seen[k] = f.Name
	}
	return nil
}
