// Package gcp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package gcp

// XGatewaySpec defines model for XGatewaySpec.
type XGatewaySpec struct {
	AllowedPorts *[]struct {
		Port     int    `json:"port"`
		Protocol string `json:"protocol"`
	} `json:"allowedPorts,omitempty"`
	DiskSizeGB       *int      `json:"diskSizeGB,omitempty"`
	DnsHostnames     *[]string `json:"dnsHostnames,omitempty"`
	Image            *string   `json:"image,omitempty"`
	MachineType      string    `json:"machineType"`
	Region           string    `json:"region"`
	ReservedIP       *bool     `json:"reservedIP,omitempty"`
	SecretId         *string   `json:"secretId,omitempty"`
	ServiceAccountId *string   `json:"serviceAccountId,omitempty"`
	Spot             *bool     `json:"spot,omitempty"`
	SubnetCIDR       string    `json:"subnetCIDR"`
	UserData         *string   `json:"userData,omitempty"`
	WgKeySecretRef   *struct {
		Key  string `json:"key"`
		Name string `json:"name"`
	} `json:"wgKeySecretRef,omitempty"`
	WgListenPort int    `json:"wgListenPort"`
	Zone         string `json:"zone"`
}

// XGatewayStatus defines model for XGatewayStatus.
type XGatewayStatus struct {
	Address             *string `json:"address,omitempty"`
	ServiceAccountEmail *string `json:"serviceAccountEmail,omitempty"`
}
