// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package gcpmembers

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"k8s.io/apimachinery/pkg/types"
)

// NewMockDeps creates a new instance of MockDeps. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeps(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeps {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockDeps{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockDeps is an autogenerated mock type for the Deps type
type MockDeps struct {
	mock.Mock
}

type MockDeps_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeps) EXPECT() *MockDeps_Expecter {
	return &MockDeps_Expecter{mock: &_m.Mock}
}

// CompositeSynced provides a mock function for the type MockDeps
func (_mock *MockDeps) CompositeSynced(ctx context.Context, gatewayNamespace string, gatewayName string) (bool, string, error) {
	ret := _mock.Called(ctx, gatewayNamespace, gatewayName)

	if len(ret) == 0 {
		panic("no return value specified for CompositeSynced")
	}

	var r0 bool
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, string, error)); ok {
		return returnFunc(ctx, gatewayNamespace, gatewayName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, gatewayNamespace, gatewayName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) string); ok {
		r1 = returnFunc(ctx, gatewayNamespace, gatewayName)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, gatewayNamespace, gatewayName)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockDeps_CompositeSynced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompositeSynced'
type MockDeps_CompositeSynced_Call struct {
	*mock.Call
}

// CompositeSynced is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayNamespace string
//   - gatewayName string
func (_e *MockDeps_Expecter) CompositeSynced(ctx any, gatewayNamespace any, gatewayName any) *MockDeps_CompositeSynced_Call {
	return &MockDeps_CompositeSynced_Call{Call: _e.mock.On("CompositeSynced", ctx, gatewayNamespace, gatewayName)}
}

func (_c *MockDeps_CompositeSynced_Call) Run(run func(ctx context.Context, gatewayNamespace string, gatewayName string)) *MockDeps_CompositeSynced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeps_CompositeSynced_Call) Return(b bool, s string, err error) *MockDeps_CompositeSynced_Call {
	_c.Call.Return(b, s, err)
	return _c
}

func (_c *MockDeps_CompositeSynced_Call) RunAndReturn(run func(ctx context.Context, gatewayNamespace string, gatewayName string) (bool, string, error)) *MockDeps_CompositeSynced_Call {
	_c.Call.Return(run)
	return _c
}

// ConfirmManagedResourcesAbsent provides a mock function for the type MockDeps
func (_mock *MockDeps) ConfirmManagedResourcesAbsent(ctx context.Context, names ManagedResourceNames) (bool, string, error) {
	ret := _mock.Called(ctx, names)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmManagedResourcesAbsent")
	}

	var r0 bool
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ManagedResourceNames) (bool, string, error)); ok {
		return returnFunc(ctx, names)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ManagedResourceNames) bool); ok {
		r0 = returnFunc(ctx, names)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ManagedResourceNames) string); ok {
		r1 = returnFunc(ctx, names)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, ManagedResourceNames) error); ok {
		r2 = returnFunc(ctx, names)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockDeps_ConfirmManagedResourcesAbsent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmManagedResourcesAbsent'
type MockDeps_ConfirmManagedResourcesAbsent_Call struct {
	*mock.Call
}

// ConfirmManagedResourcesAbsent is a helper method to define mock.On call
//   - ctx context.Context
//   - names ManagedResourceNames
func (_e *MockDeps_Expecter) ConfirmManagedResourcesAbsent(ctx any, names any) *MockDeps_ConfirmManagedResourcesAbsent_Call {
	return &MockDeps_ConfirmManagedResourcesAbsent_Call{Call: _e.mock.On("ConfirmManagedResourcesAbsent", ctx, names)}
}

func (_c *MockDeps_ConfirmManagedResourcesAbsent_Call) Run(run func(ctx context.Context, names ManagedResourceNames)) *MockDeps_ConfirmManagedResourcesAbsent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ManagedResourceNames
		if args[1] != nil {
			arg1 = args[1].(ManagedResourceNames)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeps_ConfirmManagedResourcesAbsent_Call) Return(b bool, s string, err error) *MockDeps_ConfirmManagedResourcesAbsent_Call {
	_c.Call.Return(b, s, err)
	return _c
}

func (_c *MockDeps_ConfirmManagedResourcesAbsent_Call) RunAndReturn(run func(ctx context.Context, names ManagedResourceNames) (bool, string, error)) *MockDeps_ConfirmManagedResourcesAbsent_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRecord provides a mock function for the type MockDeps
func (_mock *MockDeps) CreateRecord(ctx context.Context, gatewayNamespace string, gatewayName string, rec Record) error {
	ret := _mock.Called(ctx, gatewayNamespace, gatewayName, rec)

	if len(ret) == 0 {
		panic("no return value specified for CreateRecord")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, Record) error); ok {
		r0 = returnFunc(ctx, gatewayNamespace, gatewayName, rec)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeps_CreateRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRecord'
type MockDeps_CreateRecord_Call struct {
	*mock.Call
}

// CreateRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayNamespace string
//   - gatewayName string
//   - rec Record
func (_e *MockDeps_Expecter) CreateRecord(ctx any, gatewayNamespace any, gatewayName any, rec any) *MockDeps_CreateRecord_Call {
	return &MockDeps_CreateRecord_Call{Call: _e.mock.On("CreateRecord", ctx, gatewayNamespace, gatewayName, rec)}
}

func (_c *MockDeps_CreateRecord_Call) Run(run func(ctx context.Context, gatewayNamespace string, gatewayName string, rec Record)) *MockDeps_CreateRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 Record
		if args[3] != nil {
			arg3 = args[3].(Record)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDeps_CreateRecord_Call) Return(err error) *MockDeps_CreateRecord_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeps_CreateRecord_Call) RunAndReturn(run func(ctx context.Context, gatewayNamespace string, gatewayName string, rec Record) error) *MockDeps_CreateRecord_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRecord provides a mock function for the type MockDeps
func (_mock *MockDeps) DeleteRecord(ctx context.Context, gatewayNamespace string, gatewayName string, name string, uid types.UID, resourceVersion string) error {
	ret := _mock.Called(ctx, gatewayNamespace, gatewayName, name, uid, resourceVersion)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRecord")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, types.UID, string) error); ok {
		r0 = returnFunc(ctx, gatewayNamespace, gatewayName, name, uid, resourceVersion)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeps_DeleteRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRecord'
type MockDeps_DeleteRecord_Call struct {
	*mock.Call
}

// DeleteRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayNamespace string
//   - gatewayName string
//   - name string
//   - uid types.UID
//   - resourceVersion string
func (_e *MockDeps_Expecter) DeleteRecord(ctx any, gatewayNamespace any, gatewayName any, name any, uid any, resourceVersion any) *MockDeps_DeleteRecord_Call {
	return &MockDeps_DeleteRecord_Call{Call: _e.mock.On("DeleteRecord", ctx, gatewayNamespace, gatewayName, name, uid, resourceVersion)}
}

func (_c *MockDeps_DeleteRecord_Call) Run(run func(ctx context.Context, gatewayNamespace string, gatewayName string, name string, uid types.UID, resourceVersion string)) *MockDeps_DeleteRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 types.UID
		if args[4] != nil {
			arg4 = args[4].(types.UID)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockDeps_DeleteRecord_Call) Return(err error) *MockDeps_DeleteRecord_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeps_DeleteRecord_Call) RunAndReturn(run func(ctx context.Context, gatewayNamespace string, gatewayName string, name string, uid types.UID, resourceVersion string) error) *MockDeps_DeleteRecord_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateKeypair provides a mock function for the type MockDeps
func (_mock *MockDeps) GenerateKeypair() (string, string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateKeypair")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (string, string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() string); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockDeps_GenerateKeypair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateKeypair'
type MockDeps_GenerateKeypair_Call struct {
	*mock.Call
}

// GenerateKeypair is a helper method to define mock.On call
func (_e *MockDeps_Expecter) GenerateKeypair() *MockDeps_GenerateKeypair_Call {
	return &MockDeps_GenerateKeypair_Call{Call: _e.mock.On("GenerateKeypair")}
}

func (_c *MockDeps_GenerateKeypair_Call) Run(run func()) *MockDeps_GenerateKeypair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDeps_GenerateKeypair_Call) Return(privateKey string, publicKey string, err error) *MockDeps_GenerateKeypair_Call {
	_c.Call.Return(privateKey, publicKey, err)
	return _c
}

func (_c *MockDeps_GenerateKeypair_Call) RunAndReturn(run func() (string, string, error)) *MockDeps_GenerateKeypair_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecord provides a mock function for the type MockDeps
func (_mock *MockDeps) GetRecord(ctx context.Context, gatewayNamespace string, gatewayName string, name string) (*Record, bool, error) {
	ret := _mock.Called(ctx, gatewayNamespace, gatewayName, name)

	if len(ret) == 0 {
		panic("no return value specified for GetRecord")
	}

	var r0 *Record
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*Record, bool, error)); ok {
		return returnFunc(ctx, gatewayNamespace, gatewayName, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *Record); ok {
		r0 = returnFunc(ctx, gatewayNamespace, gatewayName, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Record)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) bool); ok {
		r1 = returnFunc(ctx, gatewayNamespace, gatewayName, name)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = returnFunc(ctx, gatewayNamespace, gatewayName, name)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockDeps_GetRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecord'
type MockDeps_GetRecord_Call struct {
	*mock.Call
}

// GetRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayNamespace string
//   - gatewayName string
//   - name string
func (_e *MockDeps_Expecter) GetRecord(ctx any, gatewayNamespace any, gatewayName any, name any) *MockDeps_GetRecord_Call {
	return &MockDeps_GetRecord_Call{Call: _e.mock.On("GetRecord", ctx, gatewayNamespace, gatewayName, name)}
}

func (_c *MockDeps_GetRecord_Call) Run(run func(ctx context.Context, gatewayNamespace string, gatewayName string, name string)) *MockDeps_GetRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDeps_GetRecord_Call) Return(record *Record, b bool, err error) *MockDeps_GetRecord_Call {
	_c.Call.Return(record, b, err)
	return _c
}

func (_c *MockDeps_GetRecord_Call) RunAndReturn(run func(ctx context.Context, gatewayNamespace string, gatewayName string, name string) (*Record, bool, error)) *MockDeps_GetRecord_Call {
	_c.Call.Return(run)
	return _c
}

// ListRecordNames provides a mock function for the type MockDeps
func (_mock *MockDeps) ListRecordNames(ctx context.Context, gatewayNamespace string, gatewayName string) ([]string, error) {
	ret := _mock.Called(ctx, gatewayNamespace, gatewayName)

	if len(ret) == 0 {
		panic("no return value specified for ListRecordNames")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return returnFunc(ctx, gatewayNamespace, gatewayName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = returnFunc(ctx, gatewayNamespace, gatewayName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, gatewayNamespace, gatewayName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeps_ListRecordNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRecordNames'
type MockDeps_ListRecordNames_Call struct {
	*mock.Call
}

// ListRecordNames is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayNamespace string
//   - gatewayName string
func (_e *MockDeps_Expecter) ListRecordNames(ctx any, gatewayNamespace any, gatewayName any) *MockDeps_ListRecordNames_Call {
	return &MockDeps_ListRecordNames_Call{Call: _e.mock.On("ListRecordNames", ctx, gatewayNamespace, gatewayName)}
}

func (_c *MockDeps_ListRecordNames_Call) Run(run func(ctx context.Context, gatewayNamespace string, gatewayName string)) *MockDeps_ListRecordNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDeps_ListRecordNames_Call) Return(strings []string, err error) *MockDeps_ListRecordNames_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockDeps_ListRecordNames_Call) RunAndReturn(run func(ctx context.Context, gatewayNamespace string, gatewayName string) ([]string, error)) *MockDeps_ListRecordNames_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRecordLabels provides a mock function for the type MockDeps
func (_mock *MockDeps) UpdateRecordLabels(ctx context.Context, gatewayNamespace string, gatewayName string, name string, labels map[string]string) error {
	ret := _mock.Called(ctx, gatewayNamespace, gatewayName, name, labels)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRecordLabels")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, map[string]string) error); ok {
		r0 = returnFunc(ctx, gatewayNamespace, gatewayName, name, labels)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDeps_UpdateRecordLabels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRecordLabels'
type MockDeps_UpdateRecordLabels_Call struct {
	*mock.Call
}

// UpdateRecordLabels is a helper method to define mock.On call
//   - ctx context.Context
//   - gatewayNamespace string
//   - gatewayName string
//   - name string
//   - labels map[string]string
func (_e *MockDeps_Expecter) UpdateRecordLabels(ctx any, gatewayNamespace any, gatewayName any, name any, labels any) *MockDeps_UpdateRecordLabels_Call {
	return &MockDeps_UpdateRecordLabels_Call{Call: _e.mock.On("UpdateRecordLabels", ctx, gatewayNamespace, gatewayName, name, labels)}
}

func (_c *MockDeps_UpdateRecordLabels_Call) Run(run func(ctx context.Context, gatewayNamespace string, gatewayName string, name string, labels map[string]string)) *MockDeps_UpdateRecordLabels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 map[string]string
		if args[4] != nil {
			arg4 = args[4].(map[string]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockDeps_UpdateRecordLabels_Call) Return(err error) *MockDeps_UpdateRecordLabels_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDeps_UpdateRecordLabels_Call) RunAndReturn(run func(ctx context.Context, gatewayNamespace string, gatewayName string, name string, labels map[string]string) error) *MockDeps_UpdateRecordLabels_Call {
	_c.Call.Return(run)
	return _c
}
